#cloud-config
apt:
  preserve_sources_list: true
  sources:
    source: |
      "deb https://nginx.org/packages/ubuntu/ focal nginx"
      "deb-src https://nginx.org/packages/ubuntu/ focal nginx"
    keyid: ABF5BD827BD9BF62
    keyserver: keyserver.ubuntu.com
disk_setup:
  vdb:
    table_type: 'gpt'
    layout: True
    overwrite: True
fs_setup:
  - label: None,
    filesystem: ext4
    device: /dev/vdb1
    partition: auto
mounts:
  - [ /dev/vdb1, /etc/nginx, "auto", "defaults,nofail", "0", "0" ]
runcmd:
  - snap install core; snap refresh core
  - snap install --classic certbot
  - ln -s /snap/bin/certbot /usr/bin/certbot
  - apt-get update
  - apt-get upgrade -y
  - apt-get dist-upgrade -y
  - apt-get install nginx -y
power_state:
  mode: reboot
  timeout: 30
  condition: True